/* A hand-picked bank of evergreen feature ideas. A few are mixed into every
   gather so the wire never runs dry, even when the live feeds are slow. */
window.EVERGREEN = [
  ["Ideas", "Why do we procrastinate?", "Procrastination", "The psychology of putting things off — and what actually helps."],
  ["Ideas", "The four-day work week experiments", "Four-day week", "What trials around the world have found about working less."],
  ["Ideas", "Is boredom good for you?", "Boredom", "Researchers are reconsidering an emotion we try hard to avoid."],
  ["Ideas", "The rise and fall of the shopping mall", "Dead mall", "How America's temples of retail emptied out, and what's replacing them."],
  ["Ideas", "Daylight saving time: who still wants it?", "Daylight saving time", "The century-old clock change and the fight to end it."],
  ["Ideas", "The loneliness epidemic", "Loneliness", "Why public-health officials now treat isolation like a disease."],
  ["Ideas", "The economics of tipping", "Gratuity", "How a custom spread, and why it keeps creeping onto new screens."],
  ["Ideas", "Universal basic income trials", "Universal basic income", "What happened when people were simply given cash."],
  ["Ideas", "Why cities are banning cars from downtowns", "Car-free zone", "Pedestrian zones from Oslo to Paris, and the backlash."],
  ["Ideas", "The ethics of de-extinction", "De-extinction", "Bringing back the woolly mammoth: science, hype, and ethics."],
  ["Science", "How do octopuses think?", "Cephalopod intelligence", "Nine brains, three hearts, and an intelligence unlike ours."],
  ["Science", "The mystery of why we sleep", "Sleep", "Every animal does it, and scientists still argue about why."],
  ["Science", "Microplastics in the human body", "Microplastics", "They've been found in blood, lungs and brains. What does it mean?"],
  ["Science", "The search for life on Europa", "Europa (moon)", "An ocean under the ice of Jupiter's moon, and the missions headed there."],
  ["Science", "Gut bacteria and mood", "Gut–brain axis", "The surprising conversation between your stomach and your brain."],
  ["Science", "Why the Moon is slowly leaving us", "Tidal acceleration", "The Moon drifts about 3.8 cm farther away every year."],
  ["Science", "The science of earworms", "Earworm", "Why some songs get stuck in your head — and how to get them out."],
  ["Science", "Fungi that could save the world", "Mycoremediation", "Mushrooms that eat plastic, clean oil spills and build houses."],
  ["Science", "How animals navigate by magnetism", "Magnetoreception", "Birds, turtles and maybe even people sensing Earth's field."],
  ["Science", "The placebo effect keeps getting stronger", "Placebo", "Why fake pills seem to work better than they used to."],
  ["Science", "What happens to the body in space", "Effect of spaceflight on the human body", "Bones, eyes and genes after months in orbit."],
  ["Science", "The lost art of the night sky", "Light pollution", "Most people can no longer see the Milky Way. Does it matter?"],
  ["History", "The Great Emu War", "Emu War", "When Australia's army fought birds — and lost."],
  ["History", "The Dancing Plague of 1518", "Dancing plague of 1518", "Hundreds of people danced for days in Strasbourg. Nobody knows why."],
  ["History", "The Library of Alexandria: myth vs. history", "Library of Alexandria", "What was really lost, and when."],
  ["History", "The Carrington Event", "Carrington Event", "The 1859 solar storm that set telegraphs on fire — could it happen again?"],
  ["History", "The Radium Girls", "Radium Girls", "The factory workers who changed labor law."],
  ["History", "How the Year Without a Summer changed the world", "Year Without a Summer", "A volcano, a famine, and the birth of Frankenstein."],
  ["History", "The Great Molasses Flood", "Great Molasses Flood", "Boston, 1919: a 25-foot wave of syrup."],
  ["History", "The Voynich Manuscript", "Voynich manuscript", "A 600-year-old book nobody can read."],
  ["History", "The Christmas Truce of 1914", "Christmas truce", "When soldiers on the Western Front stopped fighting."],
  ["History", "The story of the shipping container", "Containerization", "The boring metal box that remade the global economy."],
  ["History", "The Tulip Mania", "Tulip mania", "Was the 17th-century Dutch bubble as wild as we think?"],
  ["History", "The Green Book and travel under Jim Crow", "The Negro Motorist Green Book", "The guide that helped Black Americans travel safely."],
  ["History", "The Lost Colony of Roanoke", "Roanoke Colony", "An English settlement vanished, leaving one carved word."],
  ["History", "Typhoid Mary", "Mary Mallon", "The first known healthy carrier and the ethics of quarantine."],
  ["History", "The Battle of Los Angeles", "Battle of Los Angeles", "1942: anti-aircraft guns fired at… nothing?"],
  ["History", "The history of the weekend", "Workweek and weekend", "How Saturday and Sunday became days off."],
  ["Culture", "Why vinyl records came back", "Vinyl revival", "A dead format now outsells CDs. Why?"],
  ["Culture", "The history of the crossword puzzle", "Crossword", "From a 1913 newspaper filler to a daily ritual."],
  ["Culture", "The secret life of public libraries", "Public library", "Libraries now lend tools, seeds and telescopes."],
  ["Culture", "How the laugh track was invented", "Laugh track", "The machine that told TV audiences when to laugh."],
  ["Culture", "The decline of the handwritten letter", "Letter (message)", "What we lose when nobody writes letters anymore."],
  ["Culture", "Why Wordle took over the world", "Wordle", "A simple word game and the psychology of daily rituals."],
  ["Culture", "The return of film photography", "Film photography", "Why a generation raised on phones is buying film cameras."],
  ["Culture", "The history of the emoji", "Emoji", "From Japanese pagers to a global language."],
  ["Culture", "Why we love true crime", "True crime", "The genre's boom, and the ethical questions around it."],
  ["Food", "The surprising history of sourdough", "Sourdough", "The world's oldest leavened bread and the 2020 starter boom."],
  ["Food", "Why cilantro tastes like soap to some people", "Coriander", "The genetics of a divisive herb."],
  ["Food", "The spice that built empires", "Black pepper", "How peppercorns shaped trade routes and wars."],
  ["Food", "The banana that disappeared", "Gros Michel banana", "Why the banana your grandparents ate tasted different."],
  ["Food", "The global coffee crisis", "Coffee production", "Climate change, prices and the future of your morning cup."],
  ["Food", "Lab-grown meat: where is it now?", "Cultured meat", "Approvals, bans and the struggle to scale up."],
  ["Places", "The town that lives underground", "Coober Pedy", "An opal-mining town where residents live in dugouts."],
  ["Places", "The Doomsday Seed Vault", "Svalbard Global Seed Vault", "The Arctic bunker backing up the world's crops."],
  ["Places", "Venice versus the sea", "MOSE (flood barrier)", "The billion-euro barriers holding back the tide."],
  ["Places", "The island run by its own community", "Isle of Eigg", "A Scottish island bought by its residents."],
  ["Places", "Chernobyl's wildlife", "Chernobyl Exclusion Zone", "Wolves, horses and bears in the nuclear zone."],
  ["Places", "The world's most remote inhabited island", "Tristan da Cunha", "250 people, no airport, and a six-day boat trip."],
  ["Tech", "The right to repair movement", "Right to repair", "Farmers, phone owners and the fight to fix your own stuff."],
  ["Tech", "Why the internet runs on undersea cables", "Submarine communications cable", "The fragile garden hoses carrying the world's data."],
  ["Tech", "The Y2K bug: overblown or a success?", "Year 2000 problem", "What really happened when the clocks rolled over."],
  ["Tech", "The 2038 problem", "Year 2038 problem", "The next date bug lurking in computers."],
  ["Tech", "How GPS really works", "Global Positioning System", "Satellites, atomic clocks and a dose of relativity."],
  ["Tech", "The quest for nuclear fusion", "Fusion power", "Always 30 years away? Recent milestones explained."],
  ["Tech", "Space junk", "Space debris", "Thousands of dead satellites and the risk of a cascade."],
  ["Nature", "The secret language of trees", "Mycorrhizal network", "The 'wood wide web' — and the scientists who doubt it."],
  ["Nature", "Why are the bees disappearing?", "Colony collapse disorder", "Pesticides, parasites and the state of pollinators."],
  ["Nature", "The return of the wolves to Yellowstone", "History of wolves in Yellowstone", "How one predator changed a landscape."],
  ["Nature", "The world's oldest living things", "List of oldest trees", "Bristlecone pines, clonal colonies and ancient sponges."],
  ["Nature", "Rewilding Europe", "Rewilding", "Bison, beavers and lynx are coming back. Not everyone is happy."],
  ["Nature", "The Great Pacific Garbage Patch", "Great Pacific garbage patch", "How big it really is, and the efforts to clean it."],
];
